language: go
go_import_path: github.com/vlifesystems/rulehunter
sudo: required

go:
  - 1.8
  - 1.9
  - tip

services:
  - mysql
  - postgresql

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/lawrencewoodman/roveralls
  - mysql < ci/createflow_travis_mysql.sql
  - psql -U postgres < ci/createflow_travis_postgres.sql

script:
  # Run the tests
  - chmod +x linux-test-su.sh
  - sudo ./linux-test-su.sh $GOPATH `which go` "travis upstart"
  - pwd
  # Check the test coverage
  - go test -covermode=count -coverprofile=profile.coverprofile
  - ls -la profile.coverprofile
  - cat profile.coverprofile
  - $HOME/gopath/bin/roveralls -v
  - $HOME/gopath/bin/goveralls -coverprofile=roveralls.coverprofile -service=travis-ci
  # Process the examples
  - cd examples
  - chmod +x bin/init_www_unix.sh
  - bin/init_www_unix.sh
  # Remove the following experiment because it takes too long
  - rm experiments/acmeprinters_repair016_how_many_callbacks.yaml
  - rulehunter --config=config_quick.yaml
